---
  - name: condor tarball stuff
    hosts: all
    # debugger: on_failed
    remote_user: root
    vars:
        condor_arch: x86_64
        condor_os: CentOS7
        condor_rel: 8.8.12
        #condor_srel is 8.8 if condor_rel is 8.8.12
        condor_srel: "{{condor_rel | regex_replace('^([^.]*).([^.]*).*', '\\1.\\2') }}"
        condor_tarball: "condor-{{condor_rel}}-{{condor_arch}}_{{condor_os}}-stripped.tar.gz"
        condor_url: "https://research.cs.wisc.edu/htcondor/tarball/{{condor_srel}}/{{condor_rel}}/release/{{condor_tarball}}"

    tasks:

      - name: "get {{condor_url}}"
        get_url:
          url: "{{condor_url}}"
          dest: "/var/lib/gwms-factory/condor/{{condor_tarball}}"


      - name: "untar {{condor_tarball}}"
        shell: |
          /usr/bin/tar -C /var/lib/gwms-factory/condor/ -x -z  -f /var/lib/gwms-factory/condor/{{condor_tarball}}
        args:
          warn: false


...
