---
  - name: config_factory_files.yml
    hosts: all
    remote_user: root
    vars:
    tasks:

    - name: read hostnames  
      include_vars:
        file: gwms_vars.yml
        name: gwms
    - name: set_dn_values
      set_fact:
        fact_fqdn: "{{gwms.fact_node}}{{gwms.ext}}"
        vofe_fqdn: "{{gwms.vofe_node}}{{gwms.ext}}"
        ce_fqdn: "{{gwms.ce_node}}{{gwms.ext}}"
        fact_dn: "{{gwms.dn_str}}{{gwms.fact_node}}{{gwms.ext}}"
        vofe_dn: "{{gwms.dn_str}}{{gwms.vofe_node}}{{gwms.ext}}"
        ce_dn: "{{gwms.dn_str}}{{gwms.ce_node}}{{gwms.ext}}"


    - name: edit glideinWMS.xml
      ansible.builtin.replace:
        path: /etc/gwms-factory/glideinWMS.xml
        regexp: '__VOCOLLECTOR_FQDN__'
        replace: '{{vofe_fqdn}}'

    - name: edit glideinWMS.xml 2
      ansible.builtin.replace:
        path: /etc/gwms-factory/glideinWMS.xml
        regexp: '__VOCOLLECTOR_DN__'
        replace: '{{vofe_dn}}'

    - name: edit glideinWMS.xml 3
      ansible.builtin.replace:
        path: /etc/gwms-factory/glideinWMS.xml
        regexp: '__WMSCOLLECTOR_FQDN__'
        replace: '{{fact_fqdn}}'

    - name: edit glideinWMS.xml 4
      ansible.builtin.replace:
        path: /etc/gwms-factory/glideinWMS.xml
        regexp: '__WMSCOLLECTOR_DN__'
        replace: '{{fact_dn}}'

    - name: edit glideinWMS.xml 5
      ansible.builtin.replace:
        path: /etc/gwms-factory/glideinWMS.xml
        regexp: '__CE_FQDN__'
        replace: '{{ce_fqdn}}'

    - name: edit glideinWMS.xml 6
      ansible.builtin.replace:
        path: /etc/gwms-factory/glideinWMS.xml
        regexp: '__WMSCOLLECTOR_NODE__'
        replace: '{{gwms.fact_node}}'

    - name: edit glideinWMS.xml 7
      ansible.builtin.replace:
        path: /etc/gwms-factory/glideinWMS.xml
        regexp: '__VOCOLLECTOR_NODE__'
        replace: '{{gwms.vofe_node}}'

    - name: "add info to map_file 1"
      ansible.builtin.lineinfile:
        path: /etc/condor/certs/condor_mapfile
        insertbefore: 'GSI (.*) anonymous' 
        line: 'GSI "{{fact_dn}}" factory'

    - name: "add info to map_file 2"
      ansible.builtin.lineinfile:
        path: /etc/condor/certs/condor_mapfile
        insertbefore: 'GSI (.*) anonymous' 
        line: 'GSI "{{vofe_dn}}" frontend-{{gwms.vofe_node}}'

    - name: "add info to map_file 3"
      ansible.builtin.lineinfile:
        path: /etc/condor/certs/condor_mapfile
        insertbefore: 'GSI (.*) anonymous' 
        line: 'GSI "{{ce_dn}}" compute_element'

    - name: "edit /etc/gwms-factory/config.d/Site_Entry.xml 1"
      ansible.builtin.replace:
        path: /etc/gwms-factory/config.d/Site_Entry.xml
        regexp: '__ENTRY_NAME__'
        replace: 'ce_{{gwms.ce_node}}'

    - name: "edit /etc/gwms-factory/config.d/Site_Entry.xml 2"
      ansible.builtin.replace:
        path: /etc/gwms-factory/config.d/Site_Entry.xml
        regexp: '__CE_FQDN__'
        replace: '{{ce_fqdn}}'

    - name: "edit /etc/gwms-factory/config.d/Site_Entry.xml 3"
      ansible.builtin.replace:
        path: /etc/gwms-factory/config.d/Site_Entry.xml
        regexp: '__CONDOR_ARCH__'
        replace: '{{gwms.condor_arch}}'

    - name: "edit /etc/gwms-factory/config.d/Site_Entry.xml 4"
      ansible.builtin.replace:
        path: /etc/gwms-factory/config.d/Site_Entry.xml
        regexp: '__CONDOR_OS__'
        replace: '{{gwms.condor_os}}'

    - name: "edit /etc/gwms-factory/config.d/Site_Entry.xml 4"
      ansible.builtin.replace:
        path: /etc/gwms-factory/config.d/Site_Entry.xml
        regexp: '__CONDOR_VERSION__'
        replace: '9.0.5'

...
