---
  - name: config_frontend_files.yml
    hosts: all
    remote_user: root
    vars:
    tasks:

    - name: read hostnames  
      include_vars:
        file: gwms_vars.yml
        name: gwms

    - name: set_dn_values
      set_fact:
        fact_fqdn: "{{gwms.fact_node}}{{gwms.ext}}"
        vofe_fqdn: "{{gwms.vofe_node}}{{gwms.ext}}"
        ce_fqdn: "{{gwms.ce_node}}{{gwms.ext}}"
        fact_dn: "{{gwms.dn_str}}{{gwms.fact_node}}{{gwms.ext}}"
        vofe_dn: "{{gwms.dn_str}}{{gwms.vofe_node}}{{gwms.ext}}"
        ce_dn: "{{gwms.dn_str}}{{gwms.ce_node}}{{gwms.ext}}"


    - name: edit frontend.xml
      ansible.builtin.replace:
        path: /etc/gwms-frontend/frontend.xml
        regexp: '__VOCOLLECTOR_FQDN__'
        replace: '{{vofe_fqdn}}'

    - name: edit frontend.xml 2
      ansible.builtin.replace:
        path: /etc/gwms-frontend/frontend.xml
        regexp: '__VOCOLLECTOR_DN__'
        replace: '{{vofe_dn}}'

    - name: edit frontend.xml 3
      ansible.builtin.replace:
        path: /etc/gwms-frontend/frontend.xml
        regexp: '__WMSCOLLECTOR_FQDN__'
        replace: '{{fact_fqdn}}'

    - name: edit frontend.xml 4
      ansible.builtin.replace:
        path: /etc/gwms-frontend/frontend.xml
        regexp: '__WMSCOLLECTOR_DN__'
        replace: '{{fact_dn}}'

    - name: edit frontend.xml 5
      ansible.builtin.replace:
        path: /etc/gwms-frontend/frontend.xml
        regexp: '__WMSCOLLECTOR_NODE__'
        replace: '{{gwms.fact_node}}'

    - name: edit frontend.xml 6
      ansible.builtin.replace:
        path: /etc/gwms-frontend/frontend.xml
        regexp: '__VOCOLLECTOR_NODE__'
        replace: '{{gwms.vofe_node}}'

    - name: "add info to map_file 1"
      ansible.builtin.lineinfile:
        path: /etc/condor/certs/condor_mapfile
        insertbefore: 'GSI (.*) anonymous' 
        line: 'GSI "{{fact_dn}}" factory'

    - name: "add info to map_file 2"
      ansible.builtin.lineinfile:
        path: /etc/condor/certs/condor_mapfile
        insertbefore: 'GSI (.*) anonymous' 
        line: 'GSI "{{vofe_dn}}" frontend-{{gwms.vofe_node}}'

    - name: "add info to map_file 3"
      ansible.builtin.lineinfile:
        path: /etc/condor/certs/condor_mapfile
        insertbefore: 'GSI (.*) anonymous' 
        line: 'GSI "{{ce_dn}}" compute_element'


    - name: "add info to map_file 4"
      ansible.builtin.lineinfile:
        path: /etc/condor/certs/condor_mapfile
        insertbefore: 'GSI (.*) anonymous' 
        line: 'SSL (.*{{gwms.fact_node}}.) condor'

    - name: "add info to map_file 5"
      ansible.builtin.lineinfile:
        path: /etc/condor/certs/condor_mapfile
        insertbefore: 'GSI (.*) anonymous' 
        line: 'SSL (.*) anonymous'

...
