---

- name: Start httpd, condor
  hosts: all
  become: true

  tasks:



    - name: Enable the httpd daemon in systemd
      systemd:
        name: httpd
        enabled: yes
        masked: no

    - name: Start the httpd daemon
      systemd:
        name: httpd
        state: started
        masked: no

    - name: add SSL auth to condor
      ansible.builtin.replace:
        path: /etc/condor/config.d/03_gwms_local.config
        regexp: '^(SEC_DEFAULT_AUTHENTICATION_METHODS = .+)$'
        replace: 'SEC_DEFAULT_AUTHENTICATION_METHODS = IDTOKENS,SCITOKENS,SSL,FS,GSI'

    - name: tweak SSL auth in condor
      ansible.builtin.lineinfile:
          path: /etc/condor/config.d/03_gwms_local.config
          insertbefore: BOF
          line: "AUTH_SSL_REQUIRE_CLIENT_CERTIFICATE = True"

    - name: Enable the condor daemon in systemd
      systemd:
        name: condor
        enabled: yes
        masked: no

    - name: Start the condor daemon
      systemd:
        name: httpd
        state: started
        masked: no



