---

- name: Install Docker and Docker Compose on SL7
  hosts: all
  become: true

  tasks:

    - name: install centos repo
      copy:
        src: templates/centos.repo
        dest: /etc/yum.repos.d
        mode: "u=rw,g=r,o=r"
        owner: "root"
        group: "root"

    - name: install docker repo
      copy:
        src: templates/docker-ce.repo
        dest: /etc/yum.repos.d
        mode: "u=rw,g=r,o=r"
        owner: "root"
        group: "root"


    - name: install docker-ce
      yum:
        name:
          - docker-ce
        state:
          present
      
    - name: Check if Docker is installed
      command: systemctl status docker
      register: docker_check
      ignore_errors: yes


    - name: Enable the Docker daemon in systemd
      systemd:
        name: docker
        enabled: yes
        masked: no

    - name: Start the Docker daemon
      systemd:
        name: docker
        state: started
        masked: no

    - name: Check if Docker Compose is installed
      command: docker-compose --version
      register: docker_compose_check
      ignore_errors: yes

    - name: Download and install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.21.2/docker-compose-Linux-x86_64
        dest: /usr/bin/docker-compose
        mode: 0755
      when:
        - docker_compose_check.msg is defined
        - docker_compose_check.msg.find('No such file or directory') != -1

