---
  - name: gwms factory packages install
    hosts: all
    remote_user: root
    vars:
        osg_rel: 3.5
        osg_repo: "osg"
        os_major: 7
        epel_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{os_major}}.noarch.rpm"
        osg_url: "https://repo.opensciencegrid.org/osg/{{osg_rel}}/osg-{{osg_rel}}-el{{os_major}}-release-latest.rpm"
    tasks:

    - name: install prereq packages 
      yum:
          name:
              - yum-priorities
              - osg-ca-certs
              - globus-rsl-devel
              - globus-gsi-sysconfig-devel
              - globus-gsi-callback-devel
              - globus-gss-assist-devel
              - globus-xio-gsi-driver
              - globus-gssapi-error
              - globus-io-devel
              - globus-ftp-client-devel
              - boost169-devel
              - munge-devel
          state:
              present


    - name: install condor
      yum:
          name: condor
          enablerepo: "{{osg_repo}}"
          disablerepo: "epel"

    - name: install factory
      yum:
          name: glideinwms-factory
          enablerepo: "{{osg_repo}}"
...
