---
  - name: gwms factory install and config
    hosts: all
    remote_user: root
    vars:
        osg_rel: 3.5
        osg_repo: "osg"
        os_major: 7
        vofrontend_fqdn: "fermicloud481.fnal.gov"

    tasks:

  - name: install_epel_osg_rpms.yml
    import_playbook: install_epel_osg_rpms.yml -e osg_rel=3.5 -e os_major=7

  - name: install_factory_rpms.yml
    import_playbook: install_factory_rpms.yml -e osg_repo=osg

  - name: install_factory_config_files.yml
    import_playbook: install_factory_config_files.yml

  - name: config_condor_tarballs
    import_playbook: config_condor_tarballs.yml -e condor_rel=8.9.11

  - name: config_condor_tarballs
    import_playbook: config_condor_tarballs.yml -e condor_rel=9.0.5

  - name: config glideinWMS.xml
    import_playbook: config_factory_files.yml 

  - name: http_condor_start.yml
    import_playbook: http_condor_start.yml

  - name: upgrade gwms-factory
    import_playbook: gwms_reconfig.yml -e service=gwms-factory
  
  - name: install some helpful utilities
    import_playbook: install_useful.yml
...
