---
  - name: gwms frontend packages install
    hosts: all
    remote_user: root
    vars:
        osg_rel: 3.5
        osg_repo: "osg"
        os_major: 7

    tasks:

  - name: install_epel_osg_rpms.yml
    import_playbook: install_epel_osg_rpms.yml

  - name: install_various_rpms.yml
    import_playbook: install_various_rpms.yml

  - name: install_frontend_rpms.yml
    import_playbook: install_frontend_rpms.yml

  - name: install_frontend_config_files.yml
    import_playbook: install_frontend_config_files.yml

  - name: config_frontend_files.yml
    import_playbook: config_frontend_files.yml

  - name: http_condor_start.yml
    import_playbook: http_condor_start.yml

  - name: upgrade gwms-frontend
    import_playbook: gwms_reconfig.yml -e service=gwms-frontend

  - name: install some helpful utilities
    import_playbook: install_useful.yml

...
