---
  - name: install_epel_osg_rpms.yml
    hosts: all
    remote_user: root
    vars:
        osg_rel: "3.5"
        osg_repo: "osg"
        os_major: 7
        epel_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{os_major}}.noarch.rpm"
        osg_url: "https://repo.opensciencegrid.org/osg/{{osg_rel}}/osg-{{osg_rel}}-el{{os_major}}-release-latest.rpm"
        fix1_url: "https://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/g/gfal2-util-scripts-1.6.0-6.el7.noarch.rpm"
        fix2_url: "https://download-ib01.fedoraproject.org/pub/epel/7/x86_64/Packages/p/python3-gfal2-util-1.6.0-6.el7.noarch.rpm"
    tasks:

    - name: install {{epel_url}}
      yum: name={{epel_url}}

    - name: install {{osg_url}}
      yum: 
        name: "{{osg_url}}"
        disable_gpg_check: true
        validate_certs: false

#    - name: install {{fix1_url}}
#      yum: 
#        name: "{{fix1_url}}"
#        ignore_errors: yes
#        #disable_gpg_check: true
#
#    - name: install {{fix2_url}}
#      yum: 
#        name: "{{fix2_url}}"
#        ignore_errors: yes
#        #disable_gpg_check: true
#        #
    - name: fix epel priorities
      ansible.builtin.replace:
        path: /etc/yum.repos.d/epel.repo
        regexp: '^(priority=.+)$'
        replace: 'priority=99'

...
