---
  - name: install_epel_osg_rpms.yml
    hosts: all
    remote_user: root
    vars:
        osg_rel: 3.5
        osg_repo: "osg"
        os_major: 7
        epel_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{os_major}}.noarch.rpm"
        osg_url: "https://repo.opensciencegrid.org/osg/{{osg_rel}}/osg-{{osg_rel}}-el{{os_major}}-release-latest.rpm"
    tasks:

    - name: install {{epel_url}}
      yum: name={{epel_url}}

    - name: install {{osg_url}}
      yum: name={{osg_url}}

...
