---
  - name: gwms factory packages install
    hosts: all
    remote_user: root
    vars:
        osg_repo: "osg"
    tasks:



    - name: install condor
      yum:
          name: condor
          enablerepo: "{{osg_repo}}"

    - name: install factory
      yum:
          name: glideinwms-factory
          enablerepo: "{{osg_repo}}"
...
