---
  - name: gwms vofrontend packages install
    hosts: all
    remote_user: root
    vars:
        osg_repo: "osg"
    tasks:


    - name: install vofrontend
      yum:
          name: glideinwms-vofrontend
          enablerepo: "{{osg_repo}}"

    - name: create testuser
      ansible.builtin.user:
        name: testuser
        shell: /bin/bash
        create_home: True 

...
