---
  - name: gwms factory packages install
    hosts: all
    remote_user: root
    vars:
        osg_rel: 3.5
        osg_repo: "osg"
        os_major: 7
        epel_url: "https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{os_major}}.noarch.rpm"
        osg_url: "https://repo.opensciencegrid.org/osg/{{osg_rel}}/osg-{{osg_rel}}-el{{os_major}}-release-latest.rpm"
    tasks:

    - name: install osg stuff
      yum:
          name:
              - yum-priorities
              - osg-ca-certs
          state:
              present

    - name: install boost169-devel
      yum:
          name: boost169-devel
          enablerepo: "epel"

    - name: install munge-devel
      yum:
          name: munge-devel
          enablerepo: "epel"

    - name: install condor
      yum:
          name: condor
          enablerepo: "{{osg_repo}}"
          disablerepo: "epel"

    - name: install factory
      yum:
          name: glideinwms-factory
          enablerepo: "{{osg_repo}}"
...
