---
# file: rebuild_instance.yml
# usage:
#  ansible-playbook -l openstackuigpvm01.fnal.gov rebuild_instance.yml  --vault-password-file vault_pass -e project=jobsub -e machine_instance=dbox_api_test9 -e security_group=jobsub-ports


  - name: rebuild_instance.yml
    hosts: all
    gather_facts: no
    vars:
        project: "glideinwms"
        machine_instance: "dbox_smoke_vofe"
        security_group: "gwms-ports"

        #    vars_files:
        #- vault_contents.yml

    tasks:

      - name: find token
        import_tasks: find_token_tasks.yml

      - name: rebuild instance
        import_tasks: rebuild_instance_tasks.yml
...
