---
  - name: refresh frontend playbook
    hosts: all
    remote_user: root
    tasks:
    - name: refresh proxy
      shell: |
          /root/make-proxies.sh

    - name: bounce condor
      service:
          name: condor
          enabled: yes
          state: restarted

    - name: stop server
      service:
          name:  gwms-frontend
          enabled: yes
          state: stopped

    - name: upgrade server
      shell: |
          /usr/sbin/gwms-frontend upgrade

    - name: start server
      service:
          name: gwms-frontend
          enabled: yes
          state: started
...
