---
# file: register_openstack.yml
# takes an encrypted services password file and an ansible password as input, generates an openstack token
# that can be used with the openstack API to provision resources
# usage:
#      ansible-playbook  -l openstackuigpvm01.fnal.gov register_openstack.yml  --vault-password-file vault_pass -e project=jobsub
#           parameters -e  project   default=>glideinwms
#                      --vault-password-file: ansible vault password to decrypt vault.yml
#
  - name: register_openstack.yml
    hosts: all
    gather_facts: no
    vars:
        project: "glideinwms"

    vars_files:
      - vault_contents.yml

    tasks:
      
      - name: find_token
        import_tasks: find_token_tasks.yml

      - name: import_tasks
        import_tasks: openstack_register_tasks.yml
        when: find_token.stdout == ''


...
